name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: packages/kooix-carta-mcp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: packages/kooix-carta-mcp/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Create npm pack artifact
        run: mkdir -p artifacts && npm pack --pack-destination ./artifacts

      - name: Upload release asset
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: packages/kooix-carta-mcp/artifacts/*.tgz

      - name: Upload workflow artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: carta-mcp-package
          path: packages/kooix-carta-mcp/artifacts/*.tgz
          if-no-files-found: error
